styleguide: sourcelevel/linters
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  sass-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
  - config
  - public
  - scripts
