name: Deploy Frontend

on:
  push:
    branches: 
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DO_IP_ADDRESS}} # IP address of the server you wish to ssh into
          key: ${{secrets.DO_SSH_PRIVATE_KEY}} # Private or public key of the server
          username: ${{ secrets.DO_SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/tech-community-frontend
            git add .
            git reset --hard origin/develop
            git checkout develop 
            git pull origin develop
            NODE_OPTIONS=--max_old_space_size=1024 yarn
            NODE_OPTIONS=--max_old_space_size=1024 yarn build
            
